package org.flexagent.core.multiagent;

import org.flexagent.core.memory.AgentMessage;

import java.util.Map;

/**
 * Represents a discrete agent node within a multi-agent orchestration architecture.
 */
public interface AgentNode {
    /**
     * @return the unique name of this agent node
     */
    String getName();

    /**
     * @return a description of this agent's capabilities, used by routers or supervisors
     */
    String getDescription();

    /**
     * Executes a task assigned to this agent.
     *
     * @param task the description of the task
     * @param context optional shared context payload
     * @return the response generated by this agent
     */
    AgentMessage execute(String task, Map<String, Object> context);
}
